name: flutter_page_indicator
description: Page indicator for flutter, with multiple build-in layouts.
version: 0.0.3
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_page_indicator

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
